FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY tsconfig.json prisma.config.ts ./
COPY prisma ./prisma
COPY src ./src

RUN DATABASE_URL="postgresql://postgres:postgres@localhost:5432/conectavagas" \
    npx prisma generate

ENV NODE_ENV=development
ENV PORT=3333

EXPOSE 3333

CMD ["npm", "run", "dev"]
